CANDIDATE_CAPTIONS = [
    'A dog sits calmly at the edge of a lake, staring into the water.',
    'Wet dog jumps into the water to fetch a floating stick.',
    'Two dogs tug on a rope toy near the ocean shore.',
    'A white dog lies down next to a red frisbee on the beach.',
    'Dog splashes joyfully in shallow water under the sun.',
    'A black dog leaps into the air chasing a frisbee near the shore.',
    'Dog chases birds along a rocky lakeside.',
    'A dog shakes its head near the shore a orange ball next to it.',
    'A golden retriever relaxes on a towel beside a beach umbrella.',
    'A curious dog sniffs a shell on the wet sand.',
    'A white dog shakes on the edge of a beach with an orange ball.',
    'A dog and child play fetch with a stick in the surf.',
    'Small dog rolls in the sand next to a beach ball.',
    'A dog wearing sunglasses lies on a float in the water.',
    'Wet puppy climbs onto the rocks after a swim.',
    'A fluffy dog runs past the camera on the shoreline trail.',
    'A spotted dog looks out over the lake from a wooden dock.',
    'Two dogs wrestle playfully in the sand near the water.',
    'A white puppy barks at waves crashing onto the shore.',
    'White dog playing with a red ball on the shore near the car.',
    'A soaked dog stands next to a child holding a red ball.',
    'Dog waits patiently at the dock while someone fishes.',
    'Dog paddles in the water with a bright toy in its mouth.',
    'White dog with brown ears standing near water with head not turned to one side.',
    'Dog hides a bone in the wet beach sand.',
    'Puppy plays in shallow waves as the sun sets behind it.',
    'Dog runs along the beach with seaweed in its mouth.',
    'Dog with orange ball at feet stands on shore shaking off water.',
    'A muddy dog stands proudly beside its buried treasure.',
    'Dog curls up under a tree near a lake with its toy.',
]